In [1]:
import numpy as np

In [4]:
print(np.__version__)

1.23.5


In [5]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [10]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
nz_index = np.nonzero([1,2,0,0,4,0])
print(nz_index)

(array([0, 1, 4]),)


In [14]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.83084913 0.19406201 0.16560979]
  [0.5146211  0.19469009 0.32496564]
  [0.47598145 0.95956879 0.89769072]]

 [[0.2726805  0.1178846  0.35863951]
  [0.62125224 0.4825514  0.47100588]
  [0.59492989 0.9468725  0.02140773]]

 [[0.21201359 0.48160939 0.18377104]
  [0.46087033 0.16744203 0.6700854 ]
  [0.94943762 0.61060692 0.54355001]]]


In [16]:
Z = np.random.random((10,10))
Z_min, Z_max = Z.min(), Z.max()
print(Z_min, Z_max)

0.03415537410657998 0.9943168650073897


In [19]:
Z = np.random.random(30)
Z_mean = Z.mean()
print(Z_mean)

0.5079478476125633


In [21]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [22]:
Z = np.ones((10,10))
Z[:,[0,-1]] = 0
Z[[0,-1],:] = 0
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [23]:
Z = np.ones((10,10))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [31]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [37]:
Z = np.diag(np.arange(4), k=-1)
print(Z)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]]


In [39]:
Z = np.zeros((8,8), dtype=int)
Z[1::2,::2] = 1 # 행:홀수 인덱스, 열:짝수 인덱스
Z[::2,1::2] = 1 # 행:짝수 인덱스, 열:홀수 인덱스
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [44]:
Z = np.tile(np.array([[0,1],[1,0]]), (4,4)) # 2x2 배열을 행으로 4배, 열로 4배 반복
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [47]:
Z = np.random.random((5,5))
Z = (Z - np.mean(Z)) / (np.std(Z))
print(Z)

[[ 1.15525681 -1.82279002  0.48759573 -1.66014724  0.70588337]
 [-1.7752858  -0.20275066 -0.56233327  0.04742778  0.96391352]
 [ 1.2813203   0.2871046   0.88419193  1.39485037  0.44177596]
 [ 1.33897837 -0.0112713  -0.8432204   0.11196081  0.07697178]
 [-1.08789094 -1.38360737  1.1472968  -0.06844414 -0.90678699]]


In [48]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [50]:
Z = np.arange(11)
Z[(3 < Z) * (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [63]:
print(np.sum(range(5), axis=-1)) # -1: 마지막 축

10


In [68]:
Z = np.random.uniform(-10,+10,10) # 최소값, 최대값, 개수
print(np.copysign(np.ceil(np.abs(Z)), Z))

[-8. -3.  2.  3.  2. -7. -5. -1. -3. -9.]


In [69]:
print(np.where(Z>0, np.ceil(Z), np.floor(Z))) # 조건, 참일 때 값, 거짓일 때 값

[-8. -3.  2.  3.  2. -7. -5. -1. -3. -9.]


In [72]:
Z1 = np.random.randint(0,10,10) # 최소값, 최대값, 개수
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1, Z2))

[2 3 4 6 7 8]


In [77]:
print(np.sqrt(-1))

nan


/var/folders/xj/_swws2td1j333fqkjhr5tmjr0000gn/T/ipykernel_22360/267541580.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))


In [78]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2024-03-02
2024-03-03
2024-03-04


In [83]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [84]:
A = np.ones(3) * 1
B = np.ones(3) * 2
# (A+B)*(-A/2)
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(B,A,out=B)
print(B)

[-1.5 -1.5 -1.5]


In [90]:
Z = np.random.uniform(0,10,10)
print(Z)
print(Z%1)
print(Z//1)
print(Z.astype(int))
print(np.floor(Z)) # 내림
print(np.trunc(Z)) # 소수점 버림

[9.99928687 1.65339443 2.12905963 9.34745155 4.30445123 9.44685042
 0.72720524 4.4549832  6.89917907 7.99077654]
[0.99928687 0.65339443 0.12905963 0.34745155 0.30445123 0.44685042
 0.72720524 0.4549832  0.89917907 0.99077654]
[9. 1. 2. 9. 4. 9. 0. 4. 6. 7.]
[9 1 2 9 4 9 0 4 6 7]
[9. 1. 2. 9. 4. 9. 0. 4. 6. 7.]
[9. 1. 2. 9. 4. 9. 0. 4. 6. 7.]


In [92]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [98]:
# generator
def generate():
    for x in range(10):
        yield x # return 대신 yield 사용해서 하나씩 반환

generator = generate()
print(next(generator))
print(next(generator))
print(next(generator))
print(next(generator))

Z = np.fromiter(generate(),dtype=float,count=-1) # iterable 객체, type, -1: 모든 요소 포함
print(Z)

0
1
2
3
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [105]:
Z = np.linspace(0,1,11,endpoint=False)[1:] # 최소값, 최대값, 개수, 최대값 포함 여부
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [108]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.13977738 0.26871605 0.28597738 0.28732653 0.63402435 0.6806522
 0.69239175 0.76605768 0.81868496 0.88887261]


In [110]:
Z1 = np.random.randint(0,2,5)
Z2 = np.random.randint(0,2,5)

equal = np.allclose(Z1,Z2) # 매우 작은 오차(1e-05) 허용
print(equal)
equal = np.array_equal(Z1,Z2) # 오차 허용 x
print(equal)

False
False


In [112]:
Z = np.random.random(10)
Z[Z.argmax()] = 0 # 최대값의 인덱스
print(Z)

[0.46047626 0.2959489  0.2986908  0.89270027 0.76632967 0.90748533
 0.20582495 0.         0.58696345 0.78982368]
5


In [120]:
Z = np.zeros((5,5),[('x',float),('y',float)])
Z['x'],Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [123]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


In [131]:
import scipy.spatial

Z = np.random.random((10,2)) # 최소값:0, 최댓값:1
D = scipy.spatial.distance.cdist(Z,Z) # Z 내의 모든 점들 사이의 거리
print(D)

[[0.         0.66972806 1.29659098 0.87280728 1.33467635 1.05796052
  0.37221102 1.02498519 0.51631476 0.87805156]
 [0.66972806 0.         0.62742433 0.33362653 0.66497163 0.50862992
  0.30659118 0.40926631 0.19450013 0.27227205]
 [1.29659098 0.62742433 0.         0.54233452 0.04830237 0.48694162
  0.93249253 0.36923338 0.80296208 0.46994649]
 [0.87280728 0.33362653 0.54233452 0.         0.5901782  0.190121
  0.57359925 0.18020568 0.51066358 0.10411955]
 [1.33467635 0.66497163 0.04830237 0.5901782  0.         0.5342605
  0.96857981 0.41751402 0.83658188 0.51638775]
 [1.05796052 0.50862992 0.48694162 0.190121   0.5342605  0.
  0.76344992 0.15648109 0.6943269  0.23923391]
 [0.37221102 0.30659118 0.93249253 0.57359925 0.96857981 0.76344992
  0.         0.69617888 0.14612411 0.5494611 ]
 [1.02498519 0.40926631 0.36923338 0.18020568 0.41751402 0.15648109
  0.69617888 0.         0.60324726 0.14779184]
 [0.51631476 0.19450013 0.80296208 0.51066358 0.83658188 0.6943269
  0.14612411 0.60324726 

In [140]:
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8          
                ,  , 9, 10, 11
''')

Z = np.genfromtxt(s, delimiter=',', dtype=np.int64)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


In [143]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index,value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [153]:
X = np.random.random((5,10)) # np.random.rand(5,10)
Y = X.mean(axis=1, keepdims=True) # keepdims=True: 입력 배열과 동일한 차원 유지
print(Y)

[[0.47275218]
 [0.4313859 ]
 [0.28599411]
 [0.62127224]
 [0.48998282]]


In [162]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[7 5 3]
 [7 9 7]
 [3 4 8]]
[[3 4 8]
 [7 5 3]
 [7 9 7]]


In [177]:
Z = np.random.uniform(0,1,(3,10))
z = 0.5
m = Z.flat[np.abs(Z-z).argmin()]
print(m)

0.5009565641708625


In [180]:
Z = np.arange(25).reshape(5,5)
Z[[0,1]] = Z[[1,0]]
print(Z)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [183]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z))
print(np.bincount(Z).argmax())

[8 8 3 6 8 6 2 7 1 2 1 5 4 2 3 7 6 0 2 5 6 5 4 4 9 9 1 0 8 0 2 2 1 9 2 6 0
 8 5 0 1 2 1 3 3 9 9 0 4 9]
[6 6 8 4 4 4 5 2 5 6]
2
